// Predefined mapping from biomarker type name → panel name.
// Using a static lookup rather than re-parsing maintains consistency
// when the same test is run at different labs (different formatting).

const PANEL_MAP: Record<string, string> = {
  // ── CMP ──────────────────────────────────────────────────────────────────
  Glucose: "CMP",
  "Blood Glucose": "CMP",
  "Fasting Glucose": "CMP",
  BUN: "CMP",
  "Blood Urea Nitrogen": "CMP",
  Creatinine: "CMP",
  "BUN/Creatinine Ratio": "CMP",
  "BUN/Creatinine": "CMP",
  eGFR: "CMP",
  GFR: "CMP",
  "Estimated GFR": "CMP",
  Sodium: "CMP",
  Potassium: "CMP",
  Chloride: "CMP",
  CO2: "CMP",
  Bicarbonate: "CMP",
  "Carbon Dioxide": "CMP",
  Calcium: "CMP",
  "Total Protein": "CMP",
  Albumin: "CMP",
  Globulin: "CMP",
  "A/G Ratio": "CMP",
  "Albumin/Globulin Ratio": "CMP",
  "Total Bilirubin": "CMP",
  "Direct Bilirubin": "CMP",
  "Indirect Bilirubin": "CMP",
  ALT: "CMP",
  "Alanine Aminotransferase": "CMP",
  AST: "CMP",
  "Aspartate Aminotransferase": "CMP",
  "Alkaline Phosphatase": "CMP",
  ALP: "CMP",
  "Anion Gap": "CMP",
  GGT: "CMP",
  "Gamma-Glutamyl Transferase": "CMP",

  // ── CBC ──────────────────────────────────────────────────────────────────
  WBC: "CBC",
  "White Blood Cells": "CBC",
  "White Blood Cell Count": "CBC",
  "White Blood Cell": "CBC",
  RBC: "CBC",
  "Red Blood Cells": "CBC",
  "Red Blood Cell Count": "CBC",
  "Red Blood Cell": "CBC",
  Hemoglobin: "CBC",
  HGB: "CBC",
  Hematocrit: "CBC",
  HCT: "CBC",
  MCV: "CBC",
  MCH: "CBC",
  MCHC: "CBC",
  RDW: "CBC",
  "RDW-CV": "CBC",
  "RDW-SD": "CBC",
  Platelets: "CBC",
  PLT: "CBC",
  "Platelet Count": "CBC",
  Neutrophils: "CBC",
  "Neutrophil Count": "CBC",
  "Neutrophils %": "CBC",
  "Neutrophil %": "CBC",
  "Absolute Neutrophils": "CBC",
  "Neutrophils (Absolute)": "CBC",
  Lymphocytes: "CBC",
  "Lymphocyte Count": "CBC",
  "Lymphocytes %": "CBC",
  "Lymphocyte %": "CBC",
  "Absolute Lymphocytes": "CBC",
  "Lymphocytes (Absolute)": "CBC",
  Monocytes: "CBC",
  "Monocyte Count": "CBC",
  "Monocytes %": "CBC",
  "Monocyte %": "CBC",
  "Absolute Monocytes": "CBC",
  "Monocytes (Absolute)": "CBC",
  Eosinophils: "CBC",
  "Eosinophil Count": "CBC",
  "Eosinophils %": "CBC",
  "Eosinophil %": "CBC",
  "Absolute Eosinophils": "CBC",
  "Eosinophils (Absolute)": "CBC",
  Basophils: "CBC",
  "Basophil Count": "CBC",
  "Basophils %": "CBC",
  "Basophil %": "CBC",
  "Absolute Basophils": "CBC",
  "Basophils (Absolute)": "CBC",
  "Immature Granulocytes": "CBC",
  "Immature Granulocytes %": "CBC",
  MPV: "CBC",
  PDW: "CBC",

  // ── Lipid Panel ──────────────────────────────────────────────────────────
  "Total Cholesterol": "Lipid Panel",
  Cholesterol: "Lipid Panel",
  LDL: "Lipid Panel",
  "LDL Cholesterol": "Lipid Panel",
  "LDL-C": "Lipid Panel",
  "LDL Cholesterol, Calculated": "Lipid Panel",
  HDL: "Lipid Panel",
  "HDL Cholesterol": "Lipid Panel",
  "HDL-C": "Lipid Panel",
  Triglycerides: "Lipid Panel",
  VLDL: "Lipid Panel",
  "VLDL Cholesterol": "Lipid Panel",
  "Non-HDL Cholesterol": "Lipid Panel",
  "Non-HDL-C": "Lipid Panel",
  "LDL/HDL Ratio": "Lipid Panel",
  "Total Cholesterol/HDL Ratio": "Lipid Panel",
  "Cholesterol/HDL Ratio": "Lipid Panel",
  "TC/HDL Ratio": "Lipid Panel",
  "Apolipoprotein B": "Lipid Panel",
  ApoB: "Lipid Panel",
  "Lipoprotein(a)": "Lipid Panel",
  "Lp(a)": "Lipid Panel",
  "Apolipoprotein A1": "Lipid Panel",
  ApoA1: "Lipid Panel",

  // ── Thyroid ──────────────────────────────────────────────────────────────
  TSH: "Thyroid",
  "Thyroid Stimulating Hormone": "Thyroid",
  "Free T3": "Thyroid",
  "Free Triiodothyronine": "Thyroid",
  T3: "Thyroid",
  Triiodothyronine: "Thyroid",
  "Free T4": "Thyroid",
  "Free Thyroxine": "Thyroid",
  T4: "Thyroid",
  Thyroxine: "Thyroid",
  "TPO Antibodies": "Thyroid",
  "Anti-TPO": "Thyroid",
  "Thyroid Peroxidase Antibodies": "Thyroid",
  "Thyroglobulin Antibodies": "Thyroid",
  "Anti-Thyroglobulin": "Thyroid",
  "Reverse T3": "Thyroid",
  rT3: "Thyroid",

  // ── Hormones ─────────────────────────────────────────────────────────────
  Testosterone: "Hormones",
  "Testosterone (Total)": "Hormones",
  "Total Testosterone": "Hormones",
  "Testosterone (Free)": "Hormones",
  "Free Testosterone": "Hormones",
  "Testosterone, Total": "Hormones",
  "Testosterone, Free": "Hormones",
  "DHEA-S": "Hormones",
  "DHEA-Sulfate": "Hormones",
  DHEA: "Hormones",
  Estradiol: "Hormones",
  E2: "Hormones",
  Estrogen: "Hormones",
  LH: "Hormones",
  "Luteinizing Hormone": "Hormones",
  FSH: "Hormones",
  "Follicle Stimulating Hormone": "Hormones",
  Prolactin: "Hormones",
  SHBG: "Hormones",
  "Sex Hormone Binding Globulin": "Hormones",
  Cortisol: "Hormones",
  "IGF-1": "Hormones",
  "Insulin-like Growth Factor 1": "Hormones",
  "Growth Hormone": "Hormones",
  ACTH: "Hormones",
  Progesterone: "Hormones",
  Pregnenolone: "Hormones",

  // ── Metabolic ────────────────────────────────────────────────────────────
  HbA1c: "Metabolic",
  "Hemoglobin A1c": "Metabolic",
  A1c: "Metabolic",
  "Glycated Hemoglobin": "Metabolic",
  "Fasting Insulin": "Metabolic",
  Insulin: "Metabolic",
  "C-Reactive Protein": "Metabolic",
  CRP: "Metabolic",
  "hs-CRP": "Metabolic",
  "High Sensitivity CRP": "Metabolic",
  "High-Sensitivity C-Reactive Protein": "Metabolic",
  Homocysteine: "Metabolic",
  "Uric Acid": "Metabolic",
  Fibrinogen: "Metabolic",

  // ── Vitamins & Minerals ──────────────────────────────────────────────────
  "Vitamin D": "Vitamins & Minerals",
  "Vitamin D (25-OH)": "Vitamins & Minerals",
  "25-OH Vitamin D": "Vitamins & Minerals",
  "25-Hydroxyvitamin D": "Vitamins & Minerals",
  "Vitamin D, 25-Hydroxy": "Vitamins & Minerals",
  "Vitamin B12": "Vitamins & Minerals",
  B12: "Vitamins & Minerals",
  Ferritin: "Vitamins & Minerals",
  Iron: "Vitamins & Minerals",
  "Serum Iron": "Vitamins & Minerals",
  TIBC: "Vitamins & Minerals",
  "Total Iron Binding Capacity": "Vitamins & Minerals",
  "Iron Saturation": "Vitamins & Minerals",
  "Transferrin Saturation": "Vitamins & Minerals",
  Folate: "Vitamins & Minerals",
  "Folic Acid": "Vitamins & Minerals",
  Zinc: "Vitamins & Minerals",
  Magnesium: "Vitamins & Minerals",
  Phosphorus: "Vitamins & Minerals",
  Copper: "Vitamins & Minerals",
  Selenium: "Vitamins & Minerals",
  Iodine: "Vitamins & Minerals",

  // ── Wearable ─────────────────────────────────────────────────────────────
  "HRV RMSSD": "Wearable",
  HRV: "Wearable",
  "Resting Heart Rate": "Wearable",
  RHR: "Wearable",
  "Recovery Score": "Wearable",
  "Sleep Score": "Wearable",
  SpO2: "Wearable",
  "Respiratory Rate": "Wearable",
  "Skin Temperature": "Wearable",
  "Body Battery": "Wearable",
};

export const PANEL_ORDER = [
  "CMP",
  "CBC",
  "Lipid Panel",
  "Thyroid",
  "Hormones",
  "Metabolic",
  "Vitamins & Minerals",
  "Wearable",
  "Other",
];

export function getPanelForMarker(type: string): string {
  // Exact match
  if (PANEL_MAP[type]) return PANEL_MAP[type];
  // Case-insensitive fallback
  const lower = type.toLowerCase();
  for (const [key, panel] of Object.entries(PANEL_MAP)) {
    if (key.toLowerCase() === lower) return panel;
  }
  return "Other";
}

export function groupByPanel<T extends { type: string }>(
  biomarkers: T[]
): Map<string, T[]> {
  const groups = new Map<string, T[]>();
  for (const b of biomarkers) {
    const panel = getPanelForMarker(b.type);
    if (!groups.has(panel)) groups.set(panel, []);
    groups.get(panel)!.push(b);
  }
  return groups;
}
